### ISSUE TITLE
Purge chunks reaction not generated correctly

### ISSUE THREAD

**Issue by NurdTurd** [cyberpwnn/React#12]
It should be named `action-purge-chunks.yml` on generation and not `action -purge -chunks.yml`.

Screenshot for proof:
![Screenshot](https://shel.io/f/f5A.png)

**Comment by cyberpwnn** [comment]
Interesting indeed. Thankyou for reporting this.

**Comment by NurdTurd** [comment]
No problem, happy to help! :)

**Comment by cyberpwnn** [comment]
Weird. Im not seeing that issue on the newest version. Try deleting the file then use /react reload

![capture](https://cloud.githubusercontent.com/assets/10619135/15311041/ac6d1fd6-1bc4-11e6-9c54-2bfe29c654da.PNG)

**Comment by cyberpwnn** [comment]
This will be fixed within a few hours when i update. (Fixed in code)

**Comment by NurdTurd** [comment]
Awesome!

**Comment by NurdTurd** [comment]
I've noticed the issue when I loaded the React 1.6.8 jar on the server without any config folder. It generated it that way.

**Comment by cyberpwnn** [comment]
I fixed this issue in 1.9

**Comment by NurdTurd** [comment]
Nice❗
