### ISSUE TITLE
Players' map become monitor map

### ISSUE THREAD

**Issue by Laynooor** [cyberpwnn/React#23]
![278f3c2bfc3c7a67](https://cloud.githubusercontent.com/assets/17247811/15695387/2a450d68-27d9-11e6-9b85-3f4bbbfd9114.jpg)

Several players' map occurred that problem.
Server runs spigot 1.9.4

**Comment by cyberpwnn** [comment]
Well isnt that interesting.

The only way that can happen is if the map is enchanted with
Durability 1337

If that isnt the case, this should not happen. Ill work on it to see if there are any issues i can find that would cause this
