### ISSUE TITLE
PaperSpigot support

### ISSUE THREAD

**Issue by TWSSYesterday** [cyberpwnn/React#28]
Would be nice to have some Paper Spigot implementation perhaps

**Comment by cyberpwnn** [comment]
The only feature that isnt supported at the moment is paperspigot timings.
This feature is on the backlog of things to add in, but please keep in mind that paper timings push the server extremely hard. Mainly memory. The way the timings work also lock out plugins. Essentially, i have to go the hacky route.

**Comment by TWSSYesterday** [comment]
Thanks!

**Comment by cyberpwnn** [comment]
Yeah. Resolved!
