### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by FusionCoding** [cyberpwnn/React#3]
Sometimes the mapping is not updating most if 2 players show it at the same time.

**Comment by cyberpwnn** [comment]
It isnt a problem with multiple players using the maps, its when you change the world (or server on a network) you are in. Once that happens, the only way to fix it is to turn off mapping and relog.

It is clientside, there isnt anything i can do about it at the moment unless Mojang fixes this.

Have a look here: https://github.com/cyberpwnn/React/issues/1

**Comment by philip-ulrich** [comment]
Came here to look for this. Wasn't disappointed. Your suggestion worked.

**Comment by cyberpwnn** [comment]
It is clientside, the main issue has been closed due to this discovery.
