### ISSUE TITLE
Entity-Stacker and HealthBar

### ISSUE THREAD

**Issue by WolfezzKyne** [cyberpwnn/React#30]
I use Healthbar (http://dev.bukkit.org/bukkit-plugins/health-bar/) and it might be need to reproduce this issue.

I spawned 16 creepers and killed the creeper with the stacked name. The next creeper seems to inherit the health bar as a name and the stack is removed.

Version: React 2.6.4p on latest spigot build

**Comment by cyberpwnn** [comment]
Even though the name may not show up correctly from react, react doesnt depend on the name. For example if you make a name tag and rename a stacked entity as "Bob", it should reset back to the next layer down on that stacked entity.

However i will take a look at this to see what could cause this.
