### ISSUE TITLE
Cratekeys error

### ISSUE THREAD

**Issue by TWSSYesterday** [cyberpwnn/React#31]
Ever since I uploaded and have started to use React, on my 1.8 (latest) Spigot server. I've been getting this error with Cratekeys: http://hastebin.com/mepivajuxi.avrasm
Is there a way I can disable the message?

**Comment by cyberpwnn** [comment]
Im not getting anything on that link. Paste it here with code formatting or pastebin :P

**Comment by TWSSYesterday** [comment]
Totally forgot about this, will add info tonight

**Comment by TWSSYesterday** [comment]
https://gist.github.com/TWSSYesterday/2c2f11854a0493115d5453181df0caba

**Comment by TWSSYesterday** [comment]
@cyberpwnn could you open this up again? Thanks

**Comment by cyberpwnn** [comment]
What is the issue? The error has nothing to do with react.

**Comment by TWSSYesterday** [comment]
Whenever react is on the server, it's throwing that; I assume it's working fine on the later versions and I'm missing something?

**Comment by cyberpwnn** [comment]
No. am i? lol.

**Comment by TWSSYesterday** [comment]
I'm fine with the console spam now haha; I'll just update cratekeyts, I bet it'll be fixed
