### ISSUE TITLE
Timings Issue - "Timings are off"

### ISSUE THREAD

**Issue by DataStoreRBLX** [cyberpwnn/React#32]
Recently installed this on a server running PaperSpigot, configuring it as needed. When attempting to use any of the commands related to plugin timings, or timings, from the React plugin - It states that timings are off in chat; providing no hint as to what I've done wrong. 

Whilst I may be being dull, we've enabled timings under the reactions folder - And I can't find any command to turn timings on.

Any ideas?

**Edit:** Assuming this support question should be here, considering the large bolded text at the top of the plugin page - I would have posted on the Spigot forum, but this felt like a better place.

**Comment by cyberpwnn** [comment]
I think its because you used it from the console. Here is the work around for the time being

1. If timings are on, turn them off in the console
2. use /timings on (INGAME)

That should work.

**Comment by DataStoreRBLX** [comment]
Oh, thank you. That fixed it.

However, to clarify, timings are started when the server starts up - We're using PaperSpigot. Though, I do suppose that counts as a the console.

Fair enough. Thank you for your time - It just kind of threw me, considering timings was on and such.

**Comment by cyberpwnn** [comment]
React is compatible with both, but both of them had the same issue. However this has now been fixed. Thanks for reporting it :P
