### ISSUE TITLE
NPC's dissapears

### ISSUE THREAD

**Issue by timr2000** [cyberpwnn/React#35]
Reported this bug a few days ago and still got no answer... My npc's in my hub world dissapears when i leave that world or leave the server, i think it is a problem whith the chuncks, can you please look at it?

**Comment by SwiftSwamp** [comment]
How is this an issue with React?

**Comment by SwiftSwamp** [comment]
Assuming this is because of your hard max entity limit per chunk, if you have a lot in a chunk either lower the amount of npcs per chunk or increase the limit in your auction-suppress-entities in the suppress folder.
