### ISSUE TITLE
Drop items lose.

### ISSUE THREAD

**Issue by xyblues** [cyberpwnn/React#37]
When the entity reaches 32, the drop item will be lost.
Players will lose their discarded items.
Can it be fixed?
max-entities-per-chunk-hard: 32

**Comment by SwiftSwamp** [comment]
There's nothing to fix, just increase the setting if you don't want items to be lost after more than 32 entities are in a chunk.

**Comment by xyblues** [comment]
Thank you！

**Comment by SwiftSwamp** [comment]
Of course (:
