### ISSUE TITLE
Photon causes Beds, trap doors, pressure plates, buttons, ladders and tripwire to bug and dissapepar

### ISSUE THREAD

**Issue by ssamjh** [cyberpwnn/React#38]
I made a thread a while back about on Spigot and later that day I figured out it was React, so I just deleted the react folder and went along like normal.

Now the other day I decided I need to enable photon to fix some of the lighting glitches in my survival world and it does seem to help.
Only problem is it creates some major issues with the items listed in the title.

https://www.spigotmc.org/threads/beds-trap-doors-pressure-plates-buttons-ladders-and-tripwire-hooks-removed-on-restart.181110/

**Comment by MystServer** [comment]
I can confirm this as well. I've also noticed it affects cactus and in some cases item frames

**Comment by kaboobie** [comment]
noticed this is still continuing

**Comment by cyberpwnn** [comment]
This issue has been fixed upon the removal of photon. In the future, a new implementation will fix this.
