### ISSUE TITLE
React Monitor "No Data" Stuck

### ISSUE THREAD

**Issue by chaoticaura** [cyberpwnn/React#40]
The React monitor just broke today, and is giving me [this](http://d.gcshort.xyz/12uq3/4Ju1r0Pw)

I've tried to delete the entire React folder in the plugins directory, reinstall my own minecraft, and nothing seems to be working...
[My React Config](http://d.gcshort.xyz/11Y3D/uXHOD3nj)

**Comment by SwiftSwamp** [comment]
You need to have Timings enabled in order to view that data otherwise it won't show any data, if you have PaperSpigot installed you'll need to wait 5 minutes before accurately viewing the information displayed there.

**Comment by chaoticaura** [comment]
Ah, got it! Thanks!
