### ISSUE TITLE
React now causing lag

### ISSUE THREAD

**Issue by CeIebrimbor** [cyberpwnn/React#41]
https://timings.aikar.co/v2/?id=cfcdb482d8d44347a92e0a18081f8297&start=1476400824&end=1476404513&section=lag

You will see my report. I disabled React at about 4:55pm

**Comment by CeIebrimbor** [comment]
[-]React::Task: org.cyberpwn.react.controller.TimingsController$1 (interval:20)

This was eating 93% of my tick. I tried disabling timings controller and it didn't resolve the issue so I removed React.

**Comment by BlackBeltPanda** [comment]
Same: https://timings.aikar.co/v2/?id=212c3ffaf8804345a3f791ce7cc59cbf

**Comment by SwiftSwamp** [comment]
PaperSpigot timings are extremely harsh and there's a lot more data to sort.

**Comment by CeIebrimbor** [comment]
What?... Invalid?

**Comment by SwiftSwamp** [comment]
Wrong tag, sorry about that. This isn't something we can fix, even without React PaperSpigot timings is very intensive / harsh on the server and it's recommended you always turn it off when you're not collecting data.

**Comment by BlackBeltPanda** [comment]
Strange, according to the paper devs, Paper timings have no noticeable impact on the server and they recommend them to be kept on. O.o?

**Comment by CeIebrimbor** [comment]
I can grasp that the resource won't bend around Paper, but it's not just when timings are running for Paper. I started getting pretty rough lag with 3 players online, which prompts me to turn on timings and everything screams React is killing it all. 

This TimingsController. So my first reaction is turn off this feature in React, after doing that it was the same timing issue and cause.

Can we at least get a patch to allow Paper users to disable this portion of React instead of requesting refunds for React?
