### ISSUE TITLE
React -> OutofMemory -> Server stopped

### ISSUE THREAD

**Issue by Herodennis** [cyberpwnn/React#50]
Hello,

my server use 6 GB RAM. But 300mb/6000mb are used...
Yesterday night, react stopped my server for first time (useing v4.0.9p).
Today at 16:59 again! 
Whats happend?

Serverdetails: http://pastebin.com/YnvnHiea
Servercrashlog: http://pastebin.com/HwdGe164
Pastebin Serverlog: http://pastebin.com/0YECkGwd
Plugins: ![2017-02-07_17 32 18](https://cloud.githubusercontent.com/assets/25516274/22700589/750be68a-ed5b-11e6-9806-bf89eab2667f.png)

**Comment by cyberpwnn** [comment]
Too many threads. React doesnt always use threads. You can reduce the threads it uses by doing the following
1. Turn off async tnt if you turned it on
2. In the timings-processor.yml change the threads to 2 (minimum)
